language: php
php:
  - 5.5

services:
  - postgresql

addons:
  postgresql: "9.4"
  
before_script:
  - createuser -U postgres root
  - createdb -U postgres -O root tokeneditor
  - psql -f db_schema.sql tokeneditor

